version: '3.8'

services:
  aira-hub-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: aira-hub-webui:latest
    container_name: aira-hub-webui
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - AIRA_HUB_URL=https://aira-fl8f.onrender.com
      - SECRET_KEY=changeme_in_production
      - PORT=5000
      - DEBUG=False
    volumes:
      - ./logs:/app/logs
    networks:
      - aira-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  aira-network:
    driver: bridge